### PR TITLE
Separate msgpack types from serialization details [1/2]

### PR DESCRIPTION
**Pull request by SX91**
So, a little late but still :smile: 

I've simply moved all types to this repo, leaving all ser/deser implementation back in main repo.

@iphydf any thoughts?

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/hs-msgpack-types/1)

### CODE REVIEW

**Comment by iphydf** [comment]
Check the checkbox that allows collaborators to push to the PR branch.

**Comment by SX91** [comment]
Allow edits from maintainers? Done.

**Comment by iphydf** [comment]
Can you copy/paste the Setup.lhs from one of the other repos to this one?

**Comment by SX91** [comment]
@iphydf done.

**Pull request merged**
